spring.application.name=vedio-streaming-service

server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/video-streaming
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

files.video=videos/